const escola = 'cod3r'
console.log(escola.charAt(3))
console.log(escola.charCodeAt(3))
console.log(escola.indexOf('3'))
console.log(escola.substring(1))
console.log(escola.substring(0, 3))
console.log('escola '.concat(escola).concat(' !'))
console.log(escola.replace(3, 'e'))
console.log(escola.replace(/\w/g, 'e'))
console.log('ana,maria,pedro'.split(','))
console.log('ana,maria,pedro'.split(/./))
